---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-view-ty-bnn-github-io-v1-htmlview
  failurePolicy: Fail
  name: mhtmlview.kb.io
  rules:
  - apiGroups:
    - view.ty-bnn.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - htmlviews
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-view-ty-bnn-github-io-v1-htmlview
  failurePolicy: Fail
  name: vhtmlview.kb.io
  rules:
  - apiGroups:
    - view.ty-bnn.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - htmlviews
  sideEffects: None
