# permissions for end users to edit htmlviews.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: htmlview-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: html-view
    app.kubernetes.io/part-of: html-view
    app.kubernetes.io/managed-by: kustomize
  name: htmlview-editor-role
rules:
- apiGroups:
  - view.ty-bnn.github.io
  resources:
  - htmlviews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - view.ty-bnn.github.io
  resources:
  - htmlviews/status
  verbs:
  - get
