---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - view.ty-bnn.github.io
  resources:
  - htmlviews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - view.ty-bnn.github.io
  resources:
  - htmlviews/finalizers
  verbs:
  - update
- apiGroups:
  - view.ty-bnn.github.io
  resources:
  - htmlviews/status
  verbs:
  - get
  - patch
  - update
