apiVersion: view.ty-bnn.github.io/v1
kind: HtmlView
metadata:
  labels:
    app.kubernetes.io/name: htmlview
    app.kubernetes.io/instance: htmlview-sample
    app.kubernetes.io/part-of: html-view
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: html-view
  name: htmlview-sample
spec:
  html:
    index.html: |
      <!DOCTYPE html>
      <html>
        <head>
        <title>Welcome to My WebSite!</title>
        </head>
        <body>
          <h1>Welcome to My WebSite!</h1>
          <p>This file is delivered by ty-bnn.</p>
          <p><em>Thank you for coming My WebSite.</em></p>
        </body>
      </html>
  replicas: 2
  port: 8080